### ISSUE TITLE
Issue with capitalization of elements >1 letter

### ISSUE THREAD

**Issue by andersx** [charnley/rmsd#65] opened 2020-07-21 09:11 UTC
I noticed this issue
```
atoms, coords = rmsd.get_coordinates(file_with_chlorine, "xyz")
print(atoms)
```
Gives, for example
```
['C' 'C' 'CL' 'C' 'C' 'H' 'H' 'H' 'H' 'H' 'H' 'H']
```
Even if the input file denotes chlorine as "Cl".

This means that
```
output = rmsd.set_coordinates(atoms, aligned_coordinates, title="wtf)
```
produces output with `CL` rather than `Cl`.

IMO it should either (1) preserve the input capitalization or (2) output the standard capitalization.

I will make a PR with (1) unless there are good reasons for (2), or if this is the intended behavior?

**Comment by nbehrnd** [comment] 2020-07-21 12:55
The observation is true,

because the current release (1.3.2) of calculate_rmsd.py in the project's
root directory contains three instances of .upper() (namely lines #950,
1145, and 1149).  So potentially each char of the element symbol is affected
by capitalization, and not only the first one.  Not using them there removes
the issue (I did not test if such an edit opens a new issue, thus refrain
from a PR).

As a side note, openbabel (3.1.0) called on the CLI converts an entry "cl"
in an .xyz into the "Cl", but it doesn't fix a "CL".

Norwid


On Tue, 21 Jul 2020 02:12:06 -0700
Anders Steen Christensen <notifications@github.com> wrote:

> I noticed this issue

[...]

> 
> IMO it should either (1) preserve the input capitalization or (2) output the standard capitalization.
> 
> I will make a PR with (1) unless there are good reasons for (2), or if this is the intended behavior?
>

**Comment by nbehrnd** [comment] 2020-07-27 07:36
@andersx Pending revision, the issue is addressed in [PR65](https://github.com/charnley/rmsd/pull/66).

**Comment by charnley** [comment] 2020-10-31 15:27
fixed

**Closed by charnley** 2020-10-31 15:27 UTC
Labels: bug
